services:
  db:
    container_name: postgres-db
    image: postgres:13-alpine
    ports:
      - 5432:${POSTGRES_EXTERNAL_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - net
    restart: always

  app:
    container_name: spring-batch-dojo
    stdin_open: true
    build: 
      context: .
      dockerfile: Dockerfile.dev
      args:
        - USER=$USER
    volumes:
      - $HOME/Share:/home/$USER/Share
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: on-failure
    networks:
      - net

networks:
  net:
